- name: Variable on play level
  hosts: all
  vars:
    URL: play.example.com
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: URL = {{URL}}
# Note: If we declare a varibale in PLAY level then all the tasks can access that variable.
- name: Variable from file in play level
  hosts: all
  vars_files:
    - sample-vars.yml
  tasks:
    - name: Print the URL
      ansible.builtin.debug:
        msg: URL = {{URL}}
    # We can load all the variables from a file, Since it is on play level, all the tasks can access those variables